apiVersion: v2
name: etcd-backup-operator
description: A Helm chart for the etcd-backup-operator.
version: 5.0.0
appVersion: 5.0.0
home: https://github.com/giantswarm/etcd-backup-operator
icon: https://s.giantswarm.io/app-icons/giantswarm/1/dark.svg
annotations:
  application.giantswarm.io/team: tenet
  io.giantswarm.application.team: tenet
